import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Chaitravee',
      email: 'chaitravee@gmail.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: true,
    },
    {
      name: 'Niket',
      email: 'niket@gmail.com',
      password: bcrypt.hashSync('123'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Mens clothing',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Mens clothing',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Mens clothing',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Mens clothing',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '5',
      name: 'Nike shoes',
      slug: 'nike-shoes',
      category: 'Footwear',
      image: '/images/p5.jpg',
      price: 90,
      countInStock: 10,
      brand: 'Nike',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '6',
      name: 'Apple Headphones',
      slug: 'apple-headphones',
      category: 'Electronics',
      image: '/images/p6.jpg',
      price: 550,
      countInStock: 10,
      brand: 'Apple',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '7',
      name: 'Western Wear',
      slug: 'western-wear',
      category: 'Womens clothing',
      image: '/images/p7.jpg',
      price: 25,
      countInStock: 10,
      brand: 'Istyle',
      rating: 3.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '8',
      name: 'Official suit',
      slug: 'official-suit',
      category: 'Womens clothing',
      image: '/images/p8.jpg',
      price: 20,
      countInStock: 10,
      brand: 'Official Wear',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '9',
      name: 'Dior Bag',
      slug: 'dior-bag',
      category: 'Fashion',
      image: '/images/p9.jpg',
      price: 600,
      countInStock: 10,
      brand: 'Dior',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '10',
      name: 'Diamond Ring',
      slug: 'diamond-ring',
      category: 'Jewellery',
      image: '/images/p10.jpg',
      price: 500,
      countInStock: 10,
      brand: 'Tanishq',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '11',
      name: 'Puma shoes',
      slug: 'puma-shoes',
      category: 'Footwear',
      image: '/images/p11.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Puma',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '12',
      name: 'Neckless Set',
      slug: 'neckless-set',
      category: 'Jewellery',
      image: '/images/p12.jpg',
      price: 700,
      countInStock: 10,
      brand: 'PMG',
      rating: 5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
